"""Inject defr_proxy using the RESCUE bridge (R² = 0.83).

Uses the defensive action features (Int, TklW, Fls, Crs, Aerial +
opponent mirrors) from FBref's misc match logs — available via
soccerdata stat_type="misc".

This bridge EXCEEDS the original pass-based bridge (R² = 0.83 vs 0.59)
because tackles, interceptions and fouls are the ACTUAL defensive
actions that DefR measures, not a proxy for defensive demand like pass
counts were.

Prerequisites:
    1. Run fetch_defensive_data.py to produce
       output/injection/fbref_defensive_data.parquet
    2. Phase 1 must have produced output/injection/bridge_regression_rescue.json
       (generated by the sanity check or the bridge refit step)
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd

DEFR_DIR = Path(__file__).resolve().parent
REPO_ROOT = DEFR_DIR.parent
FBREF_CSV = REPO_ROOT / "matches_classification" / "data" / "raw" / "matches_seriea.csv"
DEFENSIVE_PARQUET = DEFR_DIR / "output" / "injection" / "fbref_defensive_data.parquet"
BRIDGE_PATH = DEFR_DIR / "output" / "injection" / "bridge_regression_rescue.json"
OUT_PATH = DEFR_DIR / "output" / "injection" / "fbref_with_defr_full.parquet"


def load_bridge() -> dict:
    if not BRIDGE_PATH.exists():
        raise FileNotFoundError(
            f"{BRIDGE_PATH} not found. Run run_defr_analysis.py (Phase 1) "
            "then the bridge refit to produce the rescue bridge."
        )
    with open(BRIDGE_PATH) as f:
        return json.load(f)


def pair_opponent_stats(df: pd.DataFrame) -> pd.DataFrame:
    """Attach opponent's match stats from the mirror row."""
    df = df.copy()
    df["date"] = pd.to_datetime(df["date"])
    cols = ["sh", "sot", "dist", "xg", "poss"]
    lookup = df.set_index(["date", "team"])[cols]
    idx = pd.MultiIndex.from_arrays(
        [df["date"], df["opponent"]], names=["date", "team"]
    )
    opp = lookup.reindex(idx).reset_index(drop=True)
    opp.columns = [f"opp_{c}" for c in cols]
    return pd.concat([df.reset_index(drop=True), opp], axis=1)


def merge_defensive_data(df: pd.DataFrame) -> pd.DataFrame:
    """Merge per-match defensive stats from the misc fetch."""
    if not DEFENSIVE_PARQUET.exists():
        raise FileNotFoundError(
            f"{DEFENSIVE_PARQUET} not found. "
            "Run fetch_defensive_data.py locally first."
        )
    def_data = pd.read_parquet(DEFENSIVE_PARQUET)
    def_data["date"] = pd.to_datetime(def_data["date"])

    # Normalize team names (soccerdata vs FBref CSV may differ)
    name_map = {
        "Inter": "Internazionale",
        "AC Milan": "Milan",
    }
    def_data["team"] = def_data["team"].replace(name_map)

    # Keep only the defensive columns + opponent mirrors
    def_cols = [c for c in def_data.columns
                if c in ("tklw", "int", "fls", "fld", "crs", "crdy",
                         "opp_tklw", "opp_int", "opp_fls", "opp_fld",
                         "opp_crs", "opp_crdy", "aerial", "opp_aerial")
                or c in ("date", "team")]
    merged = df.merge(def_data[def_cols], on=["date", "team"], how="left")

    n_missing = merged[["tklw"]].isna().any(axis=1).sum() if "tklw" in merged.columns else len(merged)
    print(f"    Rows with missing defensive data: {n_missing} ({100*n_missing/len(merged):.1f}%)")
    return merged


def compute_bridge_features(df: pd.DataFrame) -> pd.DataFrame:
    """Compute the 17 rescue bridge features."""
    df = df.copy()

    # The 7 FBref-standard features (same as reduced bridge)
    df["shots_against"] = df["opp_sh"]
    df["sot_against"] = df["opp_sot"]
    df["poss_pct"] = df["poss"]
    df["goals_against"] = df["ga"]
    df["shots_for"] = df["sh"]
    df["sot_ratio_against"] = np.where(
        df["opp_sh"] > 0, df["opp_sot"] / df["opp_sh"], 0.0
    )
    df["shot_distance_proxy"] = df["opp_dist"]

    # The 10 defensive features from misc
    # Map FBref misc column names to the bridge feature names
    # (the bridge was trained on Wyscout-derived names)
    col_mapping = {
        "tklw": "tklw",        # tackles won
        "int": "intrcpt",      # interceptions → mapped to clearances in Wyscout
        "fls": "fls",          # fouls
        "crs": "crs",          # crosses
        "opp_tklw": "opp_tklw",
        "opp_int": "opp_intrcpt",
        "opp_fls": "opp_fls",
        "opp_crs": "opp_crs",
    }
    for src, dst in col_mapping.items():
        if src in df.columns:
            df[dst] = pd.to_numeric(df[src], errors="coerce").fillna(0)

    # Aerial duels — FBref misc doesn't have these directly;
    # approximate from other available columns or set to 0
    if "aerial" not in df.columns:
        df["aerial"] = 0
    if "opp_aerial" not in df.columns:
        df["opp_aerial"] = 0

    return df


def apply_bridge(df: pd.DataFrame, bridge: dict) -> pd.Series:
    """Apply the rescue bridge."""
    features = bridge["feature_names"]

    # Check which features are available
    missing = [f for f in features if f not in df.columns]
    if missing:
        print(f"    WARNING: missing features {missing}, filling with 0")
        for f in missing:
            df[f] = 0

    means = np.array([bridge["scaler_means"][f] for f in features])
    stds = np.array([bridge["scaler_stds"][f] for f in features])
    coefs = np.array([bridge["coefficients"][f] for f in features])

    X = df[features].values.astype(float)
    X_std = (X - means) / stds
    return pd.Series(X_std @ coefs + bridge["intercept"], index=df.index,
                     name="defr_proxy_full")


def add_rolling(df: pd.DataFrame) -> pd.DataFrame:
    df = df.sort_values(["team", "date"]).copy()
    df["last_5_defr_proxy_full"] = (
        df.groupby("team")["defr_proxy_full"]
        .transform(lambda x: x.shift(1).rolling(5, min_periods=2).mean())
    )
    return df


def main():
    print("=" * 64)
    print("DefR PROXY INJECTION — RESCUE BRIDGE (R² = 0.83)")
    print("=" * 64)

    bridge = load_bridge()
    print(f"\n[1] Bridge: {len(bridge['feature_names'])} features, "
          f"CV R² = {bridge['cv_r2_mean']:.3f}")

    raw = pd.read_csv(FBREF_CSV)
    print(f"[2] FBref CSV: {len(raw):,} rows")

    df = pair_opponent_stats(raw)
    print(f"[3] Opponent stats paired")

    print(f"[4] Merging defensive data from misc fetch")
    df = merge_defensive_data(df)

    print(f"[5] Computing 17 bridge features")
    df = compute_bridge_features(df)

    print(f"[6] Applying rescue bridge")
    df["defr_proxy_full"] = apply_bridge(df, bridge)

    valid = df["defr_proxy_full"].dropna()
    print(f"    Valid rows: {len(valid):,} / {len(df):,}")
    print(f"    Range: [{valid.min():+.2f}, {valid.max():+.2f}]")
    print(f"    Mean:  {valid.mean():+.2f}, Std: {valid.std():.2f}")

    print(f"[7] Adding 5-match rolling")
    df = add_rolling(df)

    print(f"\n[8] Sanity check — 2024 season rankings")
    s24 = (df[df["season"]==2024]
           .groupby("team")["defr_proxy_full"]
           .agg(["mean","count"])
           .sort_values("mean", ascending=False))
    print("  Top 5:")
    for t, r in s24.head(5).iterrows():
        print(f"    {t:25s}  {r['mean']:+7.2f}")
    print("  Bottom 5:")
    for t, r in s24.tail(5).iterrows():
        print(f"    {t:25s}  {r['mean']:+7.2f}")

    df.to_parquet(OUT_PATH, index=False)
    print(f"\n[9] Saved: {OUT_PATH.name}")


if __name__ == "__main__":
    main()
